# install the catppuccin-mocha yazi package using 'ya' cli
# ya pkg add yazi-rs/flavors:catppuccin-mocha
# ya pkg add marcosvnmelo/kanagawa-dragon
# ya pkg add gosxrgxx/flexoki-dark

[flavor]
dark = "kanagawa-dragon"
# dark = "flexoki-dark"
# dark = "catppuccin-mocha"
