# https://github.com/yazi-rs/flavors
# install the desired flavors package using 'ya' cli
# ya pkg add yazi-rs/flavors:catppuccin-mocha
# ya pkg add marcosvnmelo/kanagawa-dragon
# ya pkg add gosxrgxx/flexoki-dark

[flavor]
light = "catppuccin-latte"
dark = "tokyo-night"
# dark = "dracula"
# dark = "kanagawa-dragon"
# dark = "flexoki-dark"
# dark = "catppuccin-mocha"
