# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
show_hidden = true
linemode = "size_and_mtime"
sort_by = "mtime"

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = "explorer.exe %*",  block = true, for = "windows" },
]
# edit = [ { run = "nvim %*"}, ]


# FOR WINDOWS, yazi looks at %APPDATA%/yazi/config so use the following symlinks
# New-Item -ItemType SymbolicLink -Path "yazi.toml" -Target "C:\Users\shiva\dotfiles\common\yazi\yazi.toml"
# New-Item -ItemType SymbolicLink -Path "theme.toml" -Target "C:\Users\shiva\dotfiles\common\yazi\theme.toml"
# New-Item -ItemType SymbolicLink -Path "keymap.toml" -Target "C:\Users\shiva\dotfiles\common\yazi\keymap.toml"

