# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
show_hidden = true
linemode = "size_and_mtime"
sort_by = "mtime"

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = "explorer.exe %*",  block = true, for = "windows" },
]
# edit = [ { run = "nvim %*"}, ]
