# Rose pine colors (add more below as needed)
love: &love "#eb6f92"
netflixred: &netflixred "#FF0000"


general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands: ['shell-exec zebar']

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: true

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'monitor_focus'

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation and keeps them
  # visible in the taskbar.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: 'cloak'

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: '10px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '5px'
    right: '5px'
    bottom: '5px'
    left: '5px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: *netflixred

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: true
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: 'square'

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: false
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: 'square'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: false

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: '1'
    display_name: "1 🏡"
    keep_alive: true
    bind_to_monitor: 0
  - name: '2'
    display_name: "2 🌟"
    keep_alive: true
    bind_to_monitor: 0
  - name: '3'
    display_name: "3 🚀"
    keep_alive: true
    bind_to_monitor: 0
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'
    display_name: " 9 📝 "
    keep_alive: true
    bind_to_monitor: 0

window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }

      # Ignores Visual Studio Popup
      # - window_process : { equals : 'devenv.exe' }

      # Ignores Dota 2
      - window_title: { equals : 'Dota 2' }

      # Ignores Debian windows
      - window_title: { regex: '.*Debian' }

      # Ignore File Explorer
      - window_title: { regex : '.*File Explorer' }
        window_class: { equals : 'CabinetWClass' }

      # Ignore Windows Settings
      - window_title: { equals: 'Settings' }
        window_class: { equals : 'ApplicationFrameWindow' }

      # Ignore Task Manager
      - window_title: { equals: 'Task Manager' }
        window_class: { equals : 'TaskManagerWindow' }

      # Ignores SFML windows
      - window_class: { equals: 'SFML_Window' }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

  # When enabled, all keybindings are disabled except for f13+shift+p which
  # returns to default keybindings.
  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['f13+shift+p']

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['f13+h', 'f13+left']
  - commands: ['focus --direction right']
    bindings: ['f13+l', 'f13+right']
  - commands: ['focus --direction up']
    bindings: ['f13+k', 'f13+up']
  - commands: ['focus --direction down']
    bindings: ['f13+j', 'f13+down']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['f13+shift+h', 'f13+shift+left']
  - commands: ['move --direction right']
    bindings: ['f13+shift+l', 'f13+shift+right']
  - commands: ['move --direction up']
    bindings: ['f13+shift+k', 'f13+shift+up']
  - commands: ['move --direction down']
    bindings: ['f13+shift+j', 'f13+shift+down']

  # Resize focused window by a percentage or pixel amount.
  - commands: ['resize --width -2%']
    bindings: ['f13+u']
  - commands: ['resize --width +2%']
    bindings: ['f13+p']
  - commands: ['resize --height +2%']
    bindings: ['f13+o']
  - commands: ['resize --height -2%']
    bindings: ['f13+i']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['f13+r']

  # Disables all keybindings until f13+shift+p is pressed again.
  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['f13+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['f13+v']

  # Change focus from tiling windows -> floating -> fullscreen.
  # - commands: ['wm-cycle-focus']
  #   bindings: ['f13+space']

  # Change the focused window to be floating.
  - commands: ['toggle-floating']
    bindings: ['f13+space']

  # Change the focused window to be floating & Centered
  - commands: ['toggle-floating --centered']
    bindings: ['f13+shift+space']

  # Change the focused window to be tiling.
  - commands: ['toggle-tiling']
    bindings: ['f13+t']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['f13+f']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['f13+m']

  # Close focused window.
  - commands: ['close']
    bindings: ['f13+control+q']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['f13+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['f13+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['f13+shift+w']

  # Launch CMD terminal. f13ernatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  # - commands: ['shell-exec %ProgramFiles%/WezTerm/wezterm.exe']
  - commands: ['shell-exec wt']
    bindings: ['f13+enter']

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ['focus --next-workspace']
    bindings: ['f13+s']
  - commands: ['focus --prev-workspace']
    bindings: ['f13+a']

  # Focus the workspace that last had focus.
  - commands: ['focus --recent-workspace']
    bindings: ['f13+d']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['f13+1']
  - commands: ['focus --workspace 2']
    bindings: ['f13+2']
  - commands: ['focus --workspace 3']
    bindings: ['f13+3']
  - commands: ['focus --workspace 4']
    bindings: ['f13+4']
  - commands: ['focus --workspace 5']
    bindings: ['f13+5']
  - commands: ['focus --workspace 6']
    bindings: ['f13+6']
  - commands: ['focus --workspace 7']
    bindings: ['f13+7']
  - commands: ['focus --workspace 8']
    bindings: ['f13+8']
  - commands: ['focus --workspace 9']
    bindings: ['f13+9']

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['f13+shift+a']
  - commands: ['move-workspace --direction right']
    bindings: ['f13+shift+f']
  - commands: ['move-workspace --direction up']
    bindings: ['f13+shift+d']
  - commands: ['move-workspace --direction down']
    bindings: ['f13+shift+s']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['f13+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['f13+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['f13+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['f13+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['f13+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['f13+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['f13+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['f13+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['f13+shift+9']
