'$schema' = 'https://starship.rs/config-schema.json'

# how to get nice new line
# [╭](surface2)\  # this is the first line of format
# [╰](surface2)\  # this will come before the $character""" (which is the last line)


# $username\
# $cmd_duration\

format = """
$directory\
$hostname\
$container\
\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$hg_branch\
$vcsh\
\
$jobs\
$sudo\
$shlvl\
$status\
\
$buf\
$bun\
$c\
$cmake\
$cobol\
$crystal\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$spack\
$swift\
$vagrant\
$vlang\
$zig\
\
(${env_var.incognito}\
$package\
$nix_shell\
$aws\
$azure\
$docker_context\
$kubernetes\
$terraform)\
\
$line_break\
\
$shell\
$character"""

add_newline = false
continuation_prompt = '[>](bold subtext0) '
# palette = "catppuccin_mocha"
# palette = "gruvbox_dark"
palette = "rose_pine"

[character]
disabled = false
success_symbol = '[\$](fg:rose)'
error_symbol = '[\$](bold fg:love)'
vimcmd_symbol = '[\$](bold fg:foam)'
vimcmd_replace_one_symbol = '[\$](bold fg:iris)'
vimcmd_replace_symbol = '[\$](bold fg:iris)'
vimcmd_visual_symbol = '[\$](bold fg:gold)'

[time]
format = ' [$time]($style) '
style = 'fg:subtext0'
disabled = true

[directory]
format = '[$path ]($style)[($read_only)]($read_only_style)'
style = 'fg:iris italic'
read_only = ' '
read_only_style = 'fg:love'
truncate_to_repo = false
use_os_path_sep = true
# truncate_to_repo = true
# use_os_path_sep = false

[username]
format = '[$user ]($style)'
style_root = 'fg:love'
style_user = 'fg:love'

[hostname]
format = '[$ssh_symbol$hostname ]($style)'
style = 'fg:love'
ssh_symbol = '@'

[container]
format = '[$hostname ]($style)'
style = 'fg:rose'

### VCS
[git_branch]
format = '[$symbol$branch ]($style)'
style = 'fg:gold'
symbol = ' '
# ignore_branches = ['main', 'master']

[hg_branch]
format = '[$symbol$branch ]($style)'
style = 'fg:rose'

[git_commit]
format = '[$tag ]($style)'
style = 'fg:rose'
tag_disabled = false
tag_symbol = ' '

[git_state]
format = '[\[$state($progress_current/$progress_total)\] ]($style)'
style = 'fg:rose'
disabled = false

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = 'fg:rose'
ahead = ' '
behind = ' '
conflicted = '󰩌 '
deleted = '󱪢 '
diverged = '󱐎 '
modified = '󱇨 '
renamed = '󱀱 '
untracked = '󰻭 '
staged = '󱧳 '
stashed = '󱧶 '
disabled = false

## SHELL STATUS
 [cmd_duration]
 format = '[ $duration ]($style)'
 style = 'fg:gold'
 show_milliseconds = false
 min_time = 2000

[jobs]
disabled = false
symbol = ' '
style = 'fg:gold'

[shlvl]
disabled = false
format = '[$symbol$shlvl]($style) '
style = 'fg:gold'
symbol = ' '
threshold = 3

[status]
format = '[$symbol$status]($style) '
style = 'fg:gold'
not_executable_symbol = ' '
not_found_symbol = ' '
sigint_symbol = ' '
signal_symbol = '󰞁 '
symbol = '󰌑 '
map_symbol = false
disabled = true

# [sudo]
# disabled = false
# format = '[$symbol ]($style)'
# style = 'fg:yellow'
# symbol = ''

### LANGUAGE VERSION INDICATORS
[buf]
format = '[$symbol($version) ]($style)'
style = 'fg:green'

[bun]
format = '[$symbol($version) ]($style)'
style = 'fg:green'

[c]
format = '[$symbol($version(-$name)) ]($style)'
style = 'fg:green'
symbol = '󰙱 '

[cmake]
format = '[$symbol($version) ]($style)'
symbol = '△'
style = 'fg:green'

[cobol]
format = '[$symbol($version) ]($style)'
style = 'fg:green'

[conda]
format = '[$symbol$environment ]($style)'
style = 'fg:green'

[crystal]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[dart]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[deno]
format = '[$symbol($version) ]($style)'
style = 'fg:green'

[dotnet]
format = '[$symbol($version)( $tfm) ]($style)'
style = 'fg:green'
symbol = ' '

[elixir]
format = '[$symbol($version \(OTP $otp_version\)) ]($style)'
style = 'fg:green'
symbol = ' '

[elm]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[erlang]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[fennel]
format = '[$symbol($version) ]($style)'
style = 'fg:green'

[golang]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[haskell]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[haxe]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[helm]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = '󱃾 '

[java]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[julia]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[kotlin]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[lua]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[nim]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[nix_shell]
format = '[$symbol$state($name) ]($style)'
style = 'fg:blue'
symbol = '󱄅 '
impure_msg = ''
pure_msg = 'pure '

[nodejs]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = '󰎙 '

[ocaml]
format = '[$symbol($version)(\($switch_indicator$switch_name\)) ]($style)'
style = 'fg:green'
symbol = ' '

[perl]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[php]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[purescript]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\)) ]($style)'
style = 'fg:green'
symbol = ' '

[red]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = '󱥒 '

[ruby]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[rust]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[scala]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[spack]
format = '[$symbol$environment ]($style)'
style = 'fg:green'

[swift]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[vagrant]
format = '[$symbol($version) ]($style)'
style = 'fg:green'

[vlang]
format = '[$symbol($version) ]($style)'
style = 'fg:green'

[zig]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

### PACKAGE INDICATORS
[package]
symbol = ' '
format = '[$symbol$version ]($style)'
style = 'fg:blue'
disabled = false

### CONTEXT INDICATORS
[env_var.incognito]
format = '[$symbol ]($style)'
variable = 'ZSH_INCOGNITO'
style = 'fg:blue'
symbol = '󰗹 '

# these have `disabled` added so we can toggle them via `starship toggle <name>`
[aws]
disabled = false
format = '[$symbol($profile)(\($region\))(\[$duration\]) ]($style)'
style = 'fg:mauve'
symbol = ' '

[azure]
disabled = true
format = '[$symbol($subscription)]($style)'
style = 'fg:mauve'
symbol = ' '

[docker_context]
disabled = false
format = '[$symbol$context ]($style)'
style = 'fg:mauve'
symbol = ' '

[gcloud]
disabled = false
format = '[$symbol$account(@$domain)(\($region\)) ]($style)'
style = 'fg:mauve'
symbol = ' '

[kubernetes]
disabled = false
format = '[$symbol($cluster/$namespace) ]($style)'
style = 'fg:mauve'
symbol = '󱃾 '

[openstack]
disabled = false
format = '[$symbol$cloud(\($project\)) ]($style)'
style = 'fg:mauve'
symbol = ' '

[pulumi]
disabled = false
format = '[$symbol$stack ]($style)'
style = 'fg:blue'

[terraform]
disabled = false
format = '[$symbol$workspace ]($style)'
style = 'fg:mauve'
symbol = '󱁢 '

### COLOR PALETTES
[palettes.rose_pine]
base = "#191724"
surface ="#1f1d2e"
overlay = "#26233a"
muted = "#6e6a86"
subtle = "#908caa"
text = "#e0def4"
love = "#eb6f92"
gold =  "#f6c177"
rose = "#ebbcba"
pine = "#31748f"
foam = "#9ccfd8"
iris = "#c4a7e7"
highlight_low = "#21202e"
highlight_med = "#403d52"
highlight_high = "#524f67"

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'
contrast = '#000000'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'


