##############################  GENERAL  ##############################
[general]
live_config_reload = true
import = [
    "./font.toml",
    # "./themes/gruber_dark.toml",
    # "./themes/kanagawa_dragon.toml",
    "./themes/black_metal.toml",
]

[env]
TERM = "xterm-256color"

[debug]
log_level = "Info"
print_events = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", action = "None" }]

##############################  STARTUP  ##############################
[terminal.shell]
program = "/usr/local/bin/fish"
# program = "/bin/bash"
# program = "tmux"

[keyboard]
bindings = [
    # { key = "l", mods = "Control|Shift", action = "ClearHistory" },
    # { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    # { key = "L", mods = "Control|Shift", chars = "l" },
    # {key = "K", mods = "Control", chars = "\u0008" },
    # Send Ctrl+Tab and Ctrl+Shift+Tab
    { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
    { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
    # Send Ctrl+/
    { key = "Slash", mods = "Control", chars = "\u001F" },
    # Send Ctrl+Enter
    { key = "Enter", mods = "Control", chars = "\u001b[13;5u" },
    { key = "Enter", mods = "Alt", action = "None" },
    # Shift+Enter is new line
    { key = "Return", mods = "Shift", chars = "\u001b\r"},
    # Pass Ctrl+t through to tmux/prefix key
    { key = "T", mods = "Control", chars = "\u0014" },
    # Pass Ctrl+j through (otherwise interpreted as Enter)
    { key = "J", mods = "Control", chars = "\u001b[74;5u" },
    # macOS: CMD+S -> Ctrl+S
    { key = "S", mods = "Command", chars = "\u0013" },
    # macOS: let CMD+Space pass through to system (Raycast/Spotlight)
    { key = "Space", mods = "Command", action = "None" },
    # macOS: CMD+N opens a new window
    { key = "N", mods = "Command", action = "CreateNewWindow" },
]


##############################  WINDOW  ##############################
[window]
opacity = 0.85
blur = true
dynamic_title = false
title = "Alacritty"
dynamic_padding = false
decorations = "Buttonless"   # "Full" | "None" | "Transparent" | "Buttonless"
resize_increments = true

[window.dimensions]
columns = 80
lines = 24

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0
