##############################  GENERAL  ##############################
[general]
live_config_reload = true
# import = ["~./kanagawa_dragon.toml"]
import = ["./catppuccin_latte.toml"]

[env]
TERM = "xterm-256color"

[debug]
log_level = "Info"
print_events = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true


##############################  STARTUP  ##############################
# [terminal.shell]
# program = "tmux"
# [terminal.shell]
# program = "wsl"
# args = ["tmux attach || tmux"]
# args = ["zellij"]

[terminal.shell]
program = "/usr/local/bin/fish"

# [shell]
# program = 'Ubuntu'
# args = ["run", "tmux"]
# program = 'powershell'

[keyboard]
bindings = [
    # {key = "K", mods = "Control", chars = "\u0008" }
    # { key = "l", mods = "Control|Shift", action = "ClearHistory" },
    # { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    # { key = "L", mods = "Control|Shift", chars = "l" },
    # {key = "K", mods = "Control", chars = "\u0008" },
    # Send Ctrl+Tab and Ctrl+Shift+Tab
    { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
    { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
    # Send Ctrl+/ 
    { key = "Slash", mods = "Control", chars = "\u001F" },
    # Send Ctrl+Enter
    { key = "Enter", mods = "Control", chars = "\u001b[13;5u" },
    { key = "Enter", mods = "Alt", action = "None" },
    # { key = "Enter", mods = "Alt", action = "ReceiveChar" },
    { key = "S", mods = "Command", chars = "\u0013" },
]

##############################  WINDOW  ##############################
[window]
opacity = 0.94
blur = true
dynamic_title = false
# title = "simple_colon"
# title = ""
# dynamic_padding = true
decorations = "Buttonless" # "Full" | "None" | "Transparent" | "Buttonless"

[window.dimensions]
columns = 80
lines = 24

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0

############################## FONT ##############################
[font]
size = 20.5
builtin_box_drawing = true

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
# family = "TX02 Nerd Font Condensed"
# family = "TX-02"
family = "Iosevka Nerd Font"
# style = "Condensed"
# family = "Iosevka"
# family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
# family = "IBM Plex Mono"
# family = "BlexMono Nerd Font"


[font.italic]
# family = "TX02 Nerd Font Condensed Oblique"
# family = "TX-02"
# style = "Condensed Oblique"
family = "Iosevka Nerd Font"
# family = "Iosevka"
# family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
# family = "IBM Plex Mono"
# family = "BlexMono Nerd Font"


[font.bold]
# style = "Bold Condensed"
# family = "TX02 Nerd Font Condensed Bold"
# family = "TX-02"
family = "Iosevka Nerd Font"
# family = "Iosevka"
# family = "Iosevka Nerd Font"
# family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
# family = "IBM Plex Mono"
# family = "BlexMono Nerd Font"

[font.bold_italic]
# style = "Bold Bold Condensed Oblique"
# family = "TX02 Nerd Font Bold Condensed Oblique"
# family = "TX-02"
family = "Iosevka Nerd Font"
# family = "Iosevka"
# family = "Iosevka Nerd Font"
# family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
# family = "IBM Plex Mono"
# family = "BlexMono Nerd Font"


############################## THEME ##############################
#### MISC.
[colors.cursor]
text = "#000000"
cursor = "#C65305"

### IMPORT THE COLOR THEME


