##############################  GENERAL  ##############################
[general]
live_config_reload = true
import = [
    "./font.toml",
    "~./kanagawa_dragon.toml",
    # "./catppuccin_latte.toml",
]

[env]
TERM = "xterm-256color"

[debug]
log_level = "Info"
print_events = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true


##############################  STARTUP  ##############################
# [terminal.shell]
# program = "tmux"
# [terminal.shell]
# program = "wsl"
# args = ["tmux attach || tmux"]
# args = ["zellij"]

[terminal.shell]
program = "/usr/local/bin/fish"

# [shell]
# program = 'Ubuntu'
# args = ["run", "tmux"]
# program = 'powershell'

[keyboard]
bindings = [
    # {key = "K", mods = "Control", chars = "\u0008" }
    # { key = "l", mods = "Control|Shift", action = "ClearHistory" },
    # { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    # { key = "L", mods = "Control|Shift", chars = "l" },
    # {key = "K", mods = "Control", chars = "\u0008" },
    # Send Ctrl+Tab and Ctrl+Shift+Tab
    { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
    { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
    # Send Ctrl+/ 
    { key = "Slash", mods = "Control", chars = "\u001F" },
    # Send Ctrl+Enter
    { key = "Enter", mods = "Control", chars = "\u001b[13;5u" },
    { key = "Enter", mods = "Alt", action = "None" },
    # { key = "Enter", mods = "Alt", action = "ReceiveChar" },
    { key = "S", mods = "Command", chars = "\u0013" },
]

##############################  WINDOW  ##############################
[window]
opacity = 0.94
blur = true
dynamic_title = false
# title = "simple_colon"
# title = ""
# dynamic_padding = true
decorations = "Buttonless" # "Full" | "None" | "Transparent" | "Buttonless"

[window.dimensions]
columns = 80
lines = 24

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0



############################## THEME ##############################
#### MISC.

