##############################  GENERAL  ##############################
[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[debug]
log_level = "Info"
print_events = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true


##############################  STARTUP  ##############################
[terminal.shell]
program = "tmux"
# [terminal.shell]
# program = "wsl"
# args = ["tmux attach || tmux"]
# args = ["zellij"]

# [shell]
# program = 'Ubuntu'
# args = ["run", "tmux"]
# program = 'powershell'

# [keyboard]
# bindings = [
# {key = "K", mods = "Control", chars = "\u0008" }
# ]

##############################  WINDOW  ##############################
[window]
opacity = 0.94
blur = true
dynamic_title = false
# title = "simple_colon"
# title = ""
# dynamic_padding = true
decorations = "Buttonless" # "Full" | "None" | "Transparent" | "Buttonless"

[window.dimensions]
columns = 80
lines = 24

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0

############################## FONT ##############################
[font]
size = 20.5
builtin_box_drawing = true

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
# family = "TX02 Nerd Font Condensed"
# family = "TX-02"
family = "Iosevka Nerd Font"
# style = "Condensed"
# family = "Iosevka"
# family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
# family = "IBM Plex Mono"
# family = "BlexMono Nerd Font"


[font.italic]
# family = "TX02 Nerd Font Condensed Oblique"
# family = "TX-02"
# style = "Condensed Oblique"
family = "Iosevka Nerd Font"
# family = "Iosevka"
# family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
# family = "IBM Plex Mono"
# family = "BlexMono Nerd Font"


[font.bold]
# style = "Bold Condensed"
# family = "TX02 Nerd Font Condensed Bold"
# family = "TX-02"
family = "Iosevka Nerd Font"
# family = "Iosevka"
# family = "Iosevka Nerd Font"
# family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
# family = "IBM Plex Mono"
# family = "BlexMono Nerd Font"

[font.bold_italic]
# style = "Bold Bold Condensed Oblique"
# family = "TX02 Nerd Font Bold Condensed Oblique"
# family = "TX-02"
family = "Iosevka Nerd Font"
# family = "Iosevka"
# family = "Iosevka Nerd Font"
# family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
# family = "IBM Plex Mono"
# family = "BlexMono Nerd Font"


############################## THEME ##############################
#### MISC.
# [colors.cursor]
# text = "#000000"
# cursor = "#ffffff"

# Kanagawa-dragon Alacritty Colors
[colors]
draw_bold_text_with_bright_colors = true


[colors.primary]
background = "#181616"
foreground = "#c5c9c5"

[colors.normal]
black = "#0d0c0c"
red = "#c4746e"
green = "#8a9a7b"
yellow = "#c4b28a"
blue = "#8ba4b0"
magenta = "#a292a3"
cyan = "#8ea4a2"
white = "#C8C093"

[colors.bright]
black = "#a6a69c"
red = "#E46876"
green = "#87a987"
yellow = "#E6C384"
blue = "#7FB4CA"
magenta = "#938AA9"
cyan = "#7AA89F"
white = "#c5c9c5"

[colors.selection]
background = "#2D4F67"
foreground = "#C8C093"

[[colors.indexed_colors]]
index = 16
color = "#b6927b"

[[colors.indexed_colors]]
index = 17
color = "#b98d7b"
