# New binding for Command + S to Ctrl + S
[[keyboard.bindings]]
chars = "\u0013"  # Ctrl + S
key = "S"
mods = "Command"


# # ALT keymaps
# alt+key doesn't work by default in alacritty
# so we are manullay telling it that whey alt+<some_key> is pressed
# treat is alt+<some_key>
[[keyboard.bindings]]
key = "A"
mods = "Alt"
chars = "\u001Ba"

[[keyboard.bindings]]
key = "B"
mods = "Alt"
chars = "\u001Bb"

[[keyboard.bindings]]
key = "C"
mods = "Alt"
chars = "\u001Bc"

[[keyboard.bindings]]
key = "D"
mods = "Alt"
chars = "\u001Bd"

[[keyboard.bindings]]
key = "E"
mods = "Alt"
chars = "\u001Be"

[[keyboard.bindings]]
key = "F"
mods = "Alt"
chars = "\u001Bf"

[[keyboard.bindings]]
key = "G"
mods = "Alt"
chars = "\u001Bg"

[[keyboard.bindings]]
key = "H"
mods = "Alt"
chars = "\u001Bh"

[[keyboard.bindings]]
key = "I"
mods = "Alt"
chars = "\u001Bi"

[[keyboard.bindings]]
key = "J"
mods = "Alt"
chars = "\u001Bj"

[[keyboard.bindings]]
key = "K"
mods = "Alt"
chars = "\u001Bk"

[[keyboard.bindings]]
key = "L"
mods = "Alt"
chars = "\u001Bl"

[[keyboard.bindings]]
key = "M"
mods = "Alt"
chars = "\u001Bm"

[[keyboard.bindings]]
key = "N"
mods = "Alt"
chars = "\u001Bn"

[[keyboard.bindings]]
key = "O"
mods = "Alt"
chars = "\u001Bo"

[[keyboard.bindings]]
key = "P"
mods = "Alt"
chars = "\u001Bp"

[[keyboard.bindings]]
key = "Q"
mods = "Alt"
chars = "\u001Bq"

[[keyboard.bindings]]
key = "R"
mods = "Alt"
chars = "\u001Br"

[[keyboard.bindings]]
key = "S"
mods = "Alt"
chars = "\u001Bs"

[[keyboard.bindings]]
key = "T"
mods = "Alt"
chars = "\u001Bt"

[[keyboard.bindings]]
key = "U"
mods = "Alt"
chars = "\u001Bu"

[[keyboard.bindings]]
key = "V"
mods = "Alt"
chars = "\u001Bv"

[[keyboard.bindings]]
key = "W"
mods = "Alt"
chars = "\u001Bw"

[[keyboard.bindings]]
key = "X"
mods = "Alt"
chars = "\u001Bx"

[[keyboard.bindings]]
key = "Y"
mods = "Alt"
chars = "\u001By"

[[keyboard.bindings]]
key = "Z"
mods = "Alt"
chars = "\u001Bz"



# [[keyboard.bindings]]
# chars = "\u0016" # Ctrl + V
# key = "V"
# mods = "Command"
#
#
# [[keyboard.bindings]]
# chars = "\u001C" # Ctrl + \
# key = "\\"
# mods = "Command"
