# New binding for Command + S to Ctrl + S
[[keyboard.bindings]]
chars = "\u0013"  # Ctrl + S
key = "S"
mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0016" # Ctrl + V
# key = "V"
# mods = "Command"
#
#
# [[keyboard.bindings]]
# chars = "\u001C" # Ctrl + \
# key = "\\"
# mods = "Command"
