# import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
import = ["~/.config/alacritty/themes/rosepine.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 18

[font.normal]
family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
style = "Regular"


[font.italic]
family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
style = "Italic"


[font.bold]
family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
opacity = 0.94
blur = true
decorations = "transparent"
dynamic_title = false
# title = "🦀"
title = ""

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
