general.import = [
    "/home/shiva/dotfiles/linux/alacritty/rosepine.toml",
    "/home/shiva/dotfiles/linux/alacritty/font.toml",
]
general.live_config_reload = true
# working_directory = '\\wsl.localhost\Ubuntu\home\shiva'
# working_directory = '\\wsl.localhost\Ubuntu\root'

[env]
TERM = "xterm-256color"

[debug]
log_level = "Info"
print_events = true

# [terminal.shell]
# program = "wsl"
# args = ["tmux attach || tmux"]
# args = ["zellij"]

# [shell]
# program = 'Ubuntu'
# args = ["run", "tmux"]
# program = 'powershell'

# [keyboard]
# bindings = [
# {key = "K", mods = "Control", chars = "\u0008" }
# ]


[window]
opacity = 0.98
blur = true
dynamic_title = false
# title = "simple_colon"
<<<<<<< HEAD
# title = ""
# dynamic_padding = true
=======
>>>>>>> refs/remotes/origin/main
decorations = "None"

[window.dimensions]
columns = 80
lines = 24


# [window.class]
# general = "Alacritty"
# instance = "Alacritty"

[window.padding]
x = 5
y = 0

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[colors]
draw_bold_text_with_bright_colors = true
