##############################  GENERAL  ##############################
# [general]
live_config_reload = true

[keyboard]
bindings = [
  # { key = "l", mods = "Control|Shift", action = "ClearHistory" },
  # { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  # { key = "L", mods = "Control|Shift", chars = "l" },
  # { key = "K", mods = "Control", chars = "\u0008" },
  # Send C-tab and C-Shift-tab
  { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
  { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
  # Send Ctrl+/ 
  { key = "Slash", mods = "Control", chars = "\u001F" },
]

[env]
TERM = "xterm-256color"

[debug]
log_level = "Info"
print_events = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true


##############################  STARTUP  ##############################
# [shell]
# program = "tmux"

# [shell]
# program = 'Ubuntu'
# args = ["run", "tmux"]
# program = 'powershell'


##############################  WINDOW  ##############################
[window]
opacity = 0.6
blur = true
dynamic_title = false
# title = "smpl;"
title = "ZEN"
# dynamic_padding = true
decorations = "Full" # "Full" | "None" | "Transparent" | "Buttonless"

[window.dimensions]
columns = 80
lines = 24

[window.class]
general = "Alacritty"
instance = "Alacritty"
[window.padding]

x = 0
y = 0


############################## THEME ##############################
[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
# background = "#1e1e2e"
# foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"


############################## FONT ##############################
[font]
size = 22
builtin_box_drawing = true

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0


[font.normal]
family = "Iosevka Nerd Font"
# family = "Iosevka"
# family = "Berkeley Mono"
# family = "BerkeleyMono Nerd Font"
# style = "Condensed"
# style = "ExtraCondensed"
# style = "UltraCondensed"
# family = "TX02 Nerd Font"
# family = "SFMono Nerd Font"
# family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus MaterialDesign Icons Plus Weather Icons"
# family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
# family = "IBM Plex Mono"
# family = "BlexMono Nerd Font"


[font.italic]
family = "Iosevka Nerd Font"
# family = "Iosevka"
# family = "Berkeley Mono"
# family = "BerkeleyMono Nerd Font"
# style = "Condensed"
# style = "ExtraCondensed Oblique"
# family = "SFMono Nerd Font"
# family = "Iosevka Nerd Font"
# family = "Iosevka"
# family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
# family = "IBM Plex Mono"
# family = "BlexMono Nerd Font"


[font.bold]
family = "Iosevka Nerd Font"
# family = "Iosevka"
# family = "Berkeley Mono"
# family = "BerkeleyMono Nerd Font"
# style = "Condensed"
# style = "ExtraCondensed Bold"
# style = "Bold"
# family = "SFMono Nerd Font"
# family = "Iosevka Nerd Font"
# family = "Iosevka"
# family = "Iosevka Nerd Font"
# family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
# family = "IBM Plex Mono"
# family = "BlexMono Nerd Font"

[font.bold_italic]
family = "Iosevka Nerd Font"
# family = "Iosevka"
# family = "Berkeley Mono"
# family = "BerkeleyMono Nerd Font"
# style = "Condensed"
# style = "ExtraCondensed Bold Oblique"
# style = "Bold Italic"
# family = "SFMono Nerd Font"
# family = "Iosevka Nerd Font"
# family = "Iosevka"
# family = "Iosevka Nerd Font"
# family = "BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"
# family = "Berkeley Mono"
# family = "JetBrainsMono Nerd Font"
# family = "IBM Plex Mono"
# family = "BlexMono Nerd Font"
