import = [
    "~/dotfiles/linux/alacritty/rosepine.toml",
    "~/dotfiles/linux/alacritty/font.toml",
]


[debug]
log_level = "Info"
print_events = true


[env]
TERM = "xterm-256color"


[window]
# opacity = 1
blur = true
opacity = 0.9
dynamic_title = true
# title = "simple_colon"
# title = ""
# dynamic_padding = true
# decorations = "None"

[window.dimensions]
columns = 80
lines = 24


[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 4
y = 0
# x = 10
# y = 10

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[mouse]
hide_when_typing = true

[colors]
draw_bold_text_with_bright_colors = true
